language: node_js

node_js:
  - node
  
services:
  - mysql
  
before_install:
  - mysql -u root --password="" < db.sql
  
install:
  - npm install -g codecov
  - npm install
  
script:
  - npm test
  - codecov
