sut:
  build: .
  dockerfile: docker/Dockerfile.test
  command: bash -c "npm test && codecov"
  links:
    - db
db:
  image: postgres
  volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
