sut:
  build: .
  dockerfile: Dockerfile.test
  command: bash -c "npm test && codecov"
  links:
    - mysql
mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - ./db:/tmp/db
  command: mysqld --init-file="/tmp/db/init.sql"